### ISSUE TITLE
To many LDAP connections

### ISSUE THREAD

**Issue by konsumate** [rabbitmq/rabbitmq-auth-backend-ldap#1]
Hey there,

You stated it yourself, the LDAP stuff can be very chatty sometimes. Using the management plugin in combination with LDAP, this can slow down the whole management interface up to not reacting anymore.

Since there is no feature reques to make it less chatty, I'm creating one hereby :) Perhaps you can think of using a auth-cache or sth similiar to avoid making connections for every request.

**Comment by gmr** [comment]
I just refactored this plugin a bit so LDAP would work in my environment. I've added caching of a single LDAP resource -- if you're able, I'd be interested if it addresses your issue:

https://github.com/gmr/rabbitmq-auth-backend-ldap

It does not cache credentials, only the open connection to the LDAP server.

**Comment by konsumate** [comment]
Good morning,

Greate news, thanks for the work.
I'll give it a try as soon as I've figured out how to build it against my current rabbitmq-server version of 3.0.1-1.

**Comment by michaelklishin** [comment]
Fixed by #4.
