### ISSUE TITLE
vhost variable substitution in tag_queries

### ISSUE THREAD

**Issue by dgmorales** [rabbitmq/rabbitmq-auth-backend-ldap#13]
Hello,

I think it would be very useful to have vhost variable substitution in tag_queries, as we have for vhost_access_query and resource_access_query.

I am not much versed in erlang, but I will try to make a PR for this. Looking at the code, it seems it can be simple.

I posted a message in rabbitmq-user about this. Here is a transcript of the scenario I described there where this would be useful:

(thread: https://groups.google.com/forum/#!topic/rabbitmq-users/VU0XAMSCeoc)

"... consider the following scenario.
- I have multiple applications on rabbitmq, each one has its own rabbitmq vhost.
- Each application has one user that can read/write/configure resources (named "sa${vhost}").
- Each application has different developers (same company, though), and I want them to manage only their own vhost (manage => readonly view of the vhost and its resources, in the production environment).
- I have a developer group per application (named "${vhost}_devs).

So i tried acls like these:

```
    {vhost_access_query, {'or', [
      {equals, {string, "${username}"}, {string, "sa${vhost}"}},
      {in_group, "cn=${vhost}_devs,ou=Users,dc=rabbittest,dc=local", "memberUid"}
    ]}},
    {resource_access_query, {equals, {string, "${username}"}, {string, "sa${vhost}"}}},
    {tag_queries, [
      {administrator, {in_group, "cn=rabbitmq_admins,ou=Users,dc=rabbittest,dc=local", "memberUid"}},
      {management, {in_group, "cn=${vhost}_devs,ou=Users,dc=rabbittest,dc=local", "memberUid"}},
    ]},
```

And then realized that it doesn't work because tag_queries does not substitute ${vhost}.

The way it is, I either :
(a) List all developer groups in the acls with 'or' (requiring a rabbitmq restart for them to manage a new vhost)
(b) Have an extra group with all developers inside it (nested groups could make this look good, but I suppose making nested groups work would be something between a pain and impossible).
(c) Set management tag to constant true, and let non-developers see an almost "empty" UI, because they don't have access to any vhost.

(obs: unfortunately, ldap basedn can't help me in this case. The developers (or even IT) in the company are spread on OUs and their common root has all company users)

Am I missing something?
Is (c) commonplace for those using authorization in the ldap plugin? It seems so much better if they could not login at all."

**Comment by dgmorales** [comment]
Ok, I took a closer look at the source and realized it's not as trivial as I thought. Getting the VHost parameter to reach do_tag_queries seems to require much more changes than I am comfortable to make/test right now, given I have near zero experience with erlang and RabbitMQ internals.

I don't think i will be able to submit a PR for this right now.

**Comment by michaelklishin** [comment]
@dgmorales no worries. This is a useful feature to have, we'll investigate as time permits.

**Comment by Ayanda-D** [comment]
`tag_queries` are executed as part of authentication, where only username and password are available for manipulation and substitution. Resources like `vhost` are used for authorization instead. If we'd like to also add `vhost` as an optional variable criterion for `tag_queries`, i.e. during authentication, we'd have to pass it from `rabbit_reader` on `#'connection.start_ok'{}` during the `auth_phase`, however, `vhost` is only available on `#'connection.open'{}`. So implementing this feature makes sense from an LDAP perspective, but introduces an AMQP conflict. According to AMQP, client only specifies a `vhost` after authentication[1] has taken place, during which LDAP `tag_queries` are executed.

[1] Advanced Message Queuing Protocol Specification, Section 3.1.2 Virtual Hosts

**Comment by michaelklishin** [comment]
Good point. In STOMP, however, vhost should be immediately available. Can we at least support this case easily?

**Comment by Ayanda-D** [comment]
@michaelklishin okay, if vhost is immediately available in STOMP, then I guess this case could be supported fairly easily. I'll continue investigating this.

**Comment by Ayanda-D** [comment]
Connection initiation requests in STOMP, inclusive of vhost and authentication credentials, are mediated into an `#amqp_params_direct{}` record. So handling this case for STOMP is basically adding handling for a rabbit server direct connection  :+1:

**Comment by hairyhum** [comment]
As far as I know, tags are mostly used by management, which means that we need to add vhost to management authentication properties.

**Comment by michaelklishin** [comment]
@hairyhum do any of the PRs for this issue need more work?

**Comment by dgmorales** [comment]
It seems to me that vhost variable substitution is still not happening in the management plugin login process. Using 3.6.2 here. See below.

( @michaelklishin  should I open a new issue instead? )

I thought that https://github.com/rabbitmq/rabbitmq-management/issues/180 by @hairyhum had added that. but see logs below:

```
=INFO REPORT==== 11-Jun-2016::09:17:34 ===
    LDAP CHECK: does app1.developer have tag management?

=INFO REPORT==== 11-Jun-2016::09:17:34 ===
    LDAP evaluating query: {in_group,"cn=${vhost}_devs,ou=Users,dc=rabbittest,dc=local",
                                     "memberUid"}

=INFO REPORT==== 11-Jun-2016::09:17:34 ===
        LDAP filling template "cn=${vhost}_devs,ou=Users,dc=rabbittest,dc=local" with
            [{username,<<"app1.developer">>},
             {user_dn,"cn=app1.developer,ou=Users,dc=rabbittest,dc=local"}]

=INFO REPORT==== 11-Jun-2016::09:17:34 ===
        LDAP template result: "cn=${vhost}_devs,ou=Users,dc=rabbittest,dc=local"

=INFO REPORT==== 11-Jun-2016::09:17:34 ===
    LDAP evaluated in_group for "cn=${vhost}_devs,ou=Users,dc=rabbittest,dc=local": {error,
                                                                                     noSuchObject}

=INFO REPORT==== 11-Jun-2016::09:17:34 ===
    LDAP DECISION: does app1.developer have tag management? {error,
                                                             noSuchObject}

...
[root@rabbit1 rabbitmq]# rabbitmqctl status |head
Status of node rabbit@rabbit1 ...
[{pid,2562},
 {running_applications,
     [{rabbitmq_management,"RabbitMQ Management Console","3.6.2"},
      {rabbitmq_web_dispatch,"RabbitMQ Web Dispatcher","3.6.2"},
      {webmachine,"webmachine","1.10.3"},
      {mochiweb,"MochiMedia Web Server","2.13.1"},
      {rabbitmq_auth_backend_ldap,"RabbitMQ LDAP Authentication Backend",
          "3.6.2"},
      {rabbitmq_management_agent,"RabbitMQ Management Agent","3.6.2"},
```

Am I misunderstanding something?  

Thank you very much for your effort on this.

**Comment by hairyhum** [comment]
@dgmorales it can be not included if API request information does not contain `vhost`.

**Comment by michaelklishin** [comment]
@dgmorales you do not log into a vhost in the management UI (and even in AMQP 0-9-1, although that is pretty much invisible to clients)

**Comment by dgmorales** [comment]
Oh! Of course. That all happens before trying to access any particular vhost.

Ok, thank you very much again.

**Comment by dgmorales** [comment]
Can you tell from your head if nested LDAP groups could/should work, as the code is today?

**Comment by michaelklishin** [comment]
@dgmorales hey, please ask questions on rabbitmq-users, our team does not use GitHub issue for questions. See https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/3.

**Comment by amitsethi5577** [comment]
Hi dgmorles - I have similar requirement .  Any luck finding the solution?
