### ISSUE TITLE
Non-existent group in tag_queries makes the whole LDAP login process fail

### ISSUE THREAD

**Issue by dgmorales** [rabbitmq/rabbitmq-auth-backend-ldap#15]
If I place a non-existent group mentioned in tag_queries (using in_group), the whole LDAP login processing fails with {error,noSuchObject}. Even if that group is irrelevant for the particular access being tested.

If I do the same (use non-existent group) in a vhost_access_query, it behaves differently: only that particular acl "rule" fails, without propagating it to the top. So the end result is just like the user were not in the group. 

I believe tag_queries should behave the same.

One may argue that I just should place the correct group in the ACL. But someone might inadvertently move the group to other OU, or even delete it, without realizing the whole LDAP integration on RabbitMQ will fall apart. It makes the LDAP plugin too vulnerable to human errors.

Example and logs follow:

```
    {tag_queries, [
      {administrator, {in_group, "cn=rabbitmq_admins,ou=Users,dc=rabbittest,dc=local", "memberUid"}},
      {management, {'or', [
         {in_group, "cn=app1_devs,ou=Users,dc=rabbittest,dc=local", "memberUid"},
         {in_group, "cn=app2_devs,ou=Wrong_Users,dc=rabbittest,dc=local", "memberUid"}
      ]}},
      {monitoring, {equals, {string, "${username}"}, {string, "rabbit.monitor"}}}
    ]},
```

In my test, "cn=app2_devs,ou=Wrong_Users,dc=rabbittest,dc=local" does not exist. Then I can't login with any LDAP user, neither to the management interface nor to AMQP ports. Here are the logs of me trying to login with rabbit.sysadmin, an user in the rabbitmq_admins group above:

(I stripped some of it for brevity)

```
=INFO REPORT==== 27-Aug-2015::15:06:51 ===
LDAP CHECK: login for rabbit.sysadmin

....
=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP DN lookup: rabbit.sysadmin -> cn=rabbit.sysadmin,ou=Users,dc=rabbittest,dc=local

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP bind succeeded: cn=rabbit.sysadmin,ou=Users,dc=rabbittest,dc=local

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP CHECK: does rabbit.sysadmin have tag administrator?

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP evaluating query: {in_group,"cn=rabbitmq_admins,ou=Users,dc=rabbittest,dc=local",
                                     "memberUid"}
... stripped ...
=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP evaluated in_group for "cn=rabbitmq_admins,ou=Users,dc=rabbittest,dc=local": true

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP DECISION: does rabbit.sysadmin have tag administrator? true

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP CHECK: does rabbit.sysadmin have tag management?

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP evaluating query: {'or',
                               [{in_group,
                                    "cn=app1_devs,ou=Users,dc=rabbittest,dc=local",
                                    "memberUid"},
                                {in_group,
                                    "cn=app2_devs,ou=Wrong_Users,dc=rabbittest,dc=local",
                                    "memberUid"}]}

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP evaluating query: {in_group,"cn=app1_devs,ou=Users,dc=rabbittest,dc=local",
                                     "memberUid"}
... stripped ...
=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP evaluated in_group for "cn=app1_devs,ou=Users,dc=rabbittest,dc=local": false

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP evaluating query: {in_group,"cn=app2_devs,ou=Wrong_Users,dc=rabbittest,dc=local",
                                     "memberUid"}

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
        LDAP filling template "cn=app2_devs,ou=Wrong_Users,dc=rabbittest,dc=local" with
            [{username,<<"rabbit.sysadmin">>},
             {user_dn,"cn=rabbit.sysadmin,ou=Users,dc=rabbittest,dc=local"}]

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
        LDAP template result: "cn=app2_devs,ou=Wrong_Users,dc=rabbittest,dc=local"

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP evaluated in_group for "cn=app2_devs,ou=Wrong_Users,dc=rabbittest,dc=local": {error,
                                                                                       noSuchObject}

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
ERROR: "    LDAP 'or' result: ~s~n" - [{error,
                                                                 noSuchObject}]

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP DECISION: does rabbit.sysadmin have tag management? {error,
                                                              noSuchObject}

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP CHECK: does rabbit.sysadmin have tag monitoring?
... stripped ...
=INFO REPORT==== 27-Aug-2015::15:06:51 ===
    LDAP DECISION: does rabbit.sysadmin have tag monitoring? false

=INFO REPORT==== 27-Aug-2015::15:06:51 ===
LDAP DECISION: login for rabbit.sysadmin: {error,noSuchObject}

=WARNING REPORT==== 27-Aug-2015::15:06:51 ===
HTTP access denied: rabbit_auth_backend_ldap failed authenticating rabbit.sysadmin: noSuchObject


=ERROR REPORT==== 27-Aug-2015::15:06:51 ===
webmachine error: path="/api/whoami"
"Unauthorized"
```

If I can be of any assistance, let me now.

**Comment by dgmorales** [comment]
Any comment on this one? Do  you think it's invalid?

**Comment by michaelklishin** [comment]
I agree that authorization query failures should not affect authentication.

**Comment by michaelklishin** [comment]
So the non-obvious thing here is that tags are associated with a user, which is meant to be returned at the authentication stage. I think tag queries that fail should simply produce an empty list or those results should be ignored. This makes most sense to me.

**Comment by Dzol** [comment]
This commit reproduces the log file extract: ee011e24bd7f241f88acb97acc8cb2ee7802567d.

Some of the test-suite fails with this change in configuration (see commit message).

This could be a simple change over a few lines [1], but we could stop error terms of the form `{error, Reason}` returned by an `eldap:search/2` from propagating, perhaps only for the `noSuchObject =:= Reason` case.

The error terms originate from [here](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L217-L218) and [here](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L233-L234).

In the former case it seems reasonable to think of an `{error, noSuchObject}` as a `false`, in fact, this is how `{error, _}` tuples are interpreted elsewhere [2].

Fix in progress.

[1] https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L389-L392

[2] https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L205-L207

**Comment by Dzol** [comment]
> I think tag queries that fail should simply produce an empty list or those results should be ignored.

@michaelklishin: Commit d39cba5e2719e687e21a121dde63d0ee060508f2 does the above. The previous comment is worth a note if you're ready to close this.

**Comment by michaelklishin** [comment]
@Dzol thank you. A note where specifically? in the docs?

**Comment by Dzol** [comment]
@michaelklishin: The one two comments above this one (four days ago).

**Comment by michaelklishin** [comment]
@Dzol yes, I understand what comment you're referring to (you can link to them, by the way). Where should we leave a note and what should it say? Or was it just an FYI?

**Comment by Dzol** [comment]
@michaelklishin: https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/15#issuecomment-201383306 was more of an FYI regarding other options for how tag queries could fail or succeed.
