### ISSUE TITLE
Cannot auth against Microsoft AD unless separate bind account used

### ISSUE THREAD

**Issue by jjmanzer** [rabbitmq/rabbitmq-auth-backend-ldap#19]
We have been experiencing issues in getting the RabbitMQ LDAP plugin to work. We have not been able to authenticate into the management plugin over HTTP. We have played with numerous different rabbitmq.config examples found on the Internet and none have worked. We are trying to auth against our Microsoft Active Domain service.

We have tried Rabbit 3.3.5/3.5.7 and erlang is R16B03-1 running on Cent7 (7.1.1503 (Core)).
We know that the user/pass is definitely valid though only as a user and not to bind to LDAP itself. For that we have to use a service account which is different than the authenticating user. We have tested access to ldap using ldapsearch and it worked.

When we make an attempt to log in with a browser we get the following in the logs (scrubbed data in boldface) ...

=INFO REPORT==== 16-Dec-2015::15:32:22 ===
    LDAP network traffic: bind request = {'BindRequest',3,
                                          "CN=user,OU=Users and Groups,DC=**xxx**,DC=**xxx**,DC=com",
                                          {simple,<<"**apassword**">>}}

=WARNING REPORT==== 16-Dec-2015::15:26:54 ===
HTTP access denied: user '**user**' - invalid credentials

=ERROR REPORT==== 16-Dec-2015::15:26:54 ===
webmachine error: path="/api/whoami"
"Unauthorized"

For the LDAP bind request part above, we see the user/pass pair are for the wrong account but we don't know how to change that. We thought other_bind was for this purpose but that seems to not be the case. Can we get support for having a separate bind account?

The config file as mentioned below (DCs were scrubbed before posting):

``````
[
  {
    rabbit,
    [
      {
        auth_backends,[
          { rabbit_auth_backend_ldap, rabbit_auth_backend_internal},
          rabbit_auth_backend_internal
        ]
      }
    ]
  },{
    rabbitmq_auth_backend_ldap,
    [
      {   servers, [ "x.x.x.x" ]
      },{ user_dn_pattern, "CN=${username},OU=Users and Groups,DC=xxxx,DC=xxxx,DC=com"
      },{ use_ssl,   false
      },{ port,      389
      },{ log,       network
      },{ tag_queries,
        [
          {   administrator, {constant, true}
          },{ management,    {constant, true} }
        ]
      }
    ]
  }
].```

Here is an example using ldapsearch that shows how our environment is working. This query results in success because we can specify the bind account. Again DCs are scrubbed as well as the service_account_password and service_account_name.

``````

ldapsearch -x -w service_account_password -h xxx.xxx.com -p 389 -b "DC=xxx,DC=xxx,DC=com" -D "service_account_name" -s sub "(sAMAccountName=user)"

```
```

**Comment by michaelklishin** [comment]
"unless" or "when"? The title seems to contradict what [was discussed on the mailing list](https://groups.google.com/forum/#!topic/rabbitmq-users/su8CznDOYFs).

**Comment by jjmanzer** [comment]
Sorry about that. So to clarify, when using a separate account (tested using the ldapsearch CLI tool) we can auth against LDAP successfully but using the RabbitMQ LDAP plugin (which does not support the feature) we cannot auth against the LDAP service.
So this is not so much a bug as a feature request I guess. The "unless" was about comparing behaviors between the ldapsearch tool and the LDAP plugin.

**Comment by jjmanzer** [comment]
So I have been experimenting with our deployment and I have learned that some of my initial statements were not accurate. I'm having some difficulty comprehending LDAP so please bear with me. I was able to  bind to my LDAP server with my user account (using ldapsearch) which previously I said I could not do. But Rabbit management/ldap plugin is still not authorizing against our service even with the config examples provided on the Rabbit support site.

**Comment by Dzol** [comment]
@jjmanzer: I gather from the discussion that the `other_bind` option is indeed what you want. You mentioned that you thought this is what the option is for but it's not set at all in the configuration file above (nor the one in the mailing list thread). Had you tried something like the following in the plugin configuration?

```
{other_bind, {DistinguishedName, Password}}
```

The above will **bind** to the LDAP server with `DistinguishedName` and `Password`, then the plugin can proceed to **authenticate/authorize** clients with the credentials they provide and the LDAP configuration that is set.

As far as I can tell this was available in the versions you report.

**Comment by michaelklishin** [comment]
I'm closing this as this seems to be covered by the features this plugin already has. Please leave a comment if you believe that's not the case or something can be meaningfully improved.
