### ISSUE TITLE
Provide examples for different LDAP Connection Scenarios

### ISSUE THREAD

**Issue by lmayorga1980** [rabbitmq/rabbitmq-auth-backend-ldap#2]
Please include different examples for different connection scenarios.
1. Basic
2. Windows (AD)
3. More Advanced

This will help other users to stop searching on google for clues. 

Thanks.

**Comment by michaelklishin** [comment]
We already have [reasonably detailed documentation](http://rabbitmq.com/ldap.html). Sadly most of the pain with using this plugin is induced by LDAP itself. We don't have the time to document LDAP.
