### ISSUE TITLE
AttributeValueAssertion with "member" fails if using Security Group members of depth > 1

### ISSUE THREAD

**Issue by dkiser** [rabbitmq/rabbitmq-auth-backend-ldap#3]
If user is a member of SecurityGroupA, and SecurityGroupA is a member of the security group Tags-Administrators, will that user ever match a tag_query correctly by deeply searching the members of groups?  The following output shows where this fails.  Is this the intended behavior?  Is there a way to change the ldap query to follow groups within groups?  This was tested using an Active Directory backend.

========== snippet of config for tag_queries ================================
{tag_queries,
        [
         {administrator, {in_group, "CN=Tags-Administrators,OU=Users & Groups,OU=Company,DC=company,DC=com"}}
        ]
}

================== auth_ldap debug output ============================
=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: bind reply = {ok,
                                        {'LDAPMessage',1,
                                         {bindResponse,
                                          {'BindResponse',success,[],[],
                                           asn1_NOVALUE,asn1_NOVALUE}},
                                         asn1_NOVALUE}}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP bind succeeded: user@domain.com

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
        LDAP filling template "${username}@domain.com" with
            [{username,<<"user">>}]

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
        LDAP template result: "user@domain.com"

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search request = {'SearchRequest',
                                            "DC=company,DC=com",
                                            wholeSubtree,neverDerefAliases,0,
                                            0,false,
                                            {equalityMatch,
                                             {'AttributeValueAssertion',
                                              "userPrincipalName",
                                              "user@domain.com"}},
                                            ["distinguishedName"]}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search reply = {ok,
                                          {'LDAPMessage',2,
                                           {searchResEntry,
                                            {'SearchResultEntry',
                                             "CN=User,OU=Users & Groups,OU=Company,DC=domain,DC=com",
                                             [{'PartialAttributeList_SEQOF',
                                               "distinguishedName",
                                               ["CN=User,OU=Users & Groups,OU=Company,DC=domain,DC=com"]}]}},
                                           asn1_NOVALUE}}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search reply = {ok,
                                          {'LDAPMessage',2,
                                           {searchResRef,
                                            ["ldaps://domain.com/CN=Configuration,DC=company,DC=com"]},
                                           asn1_NOVALUE}}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search reply = {ok,
                                          {'LDAPMessage',2,
                                           {searchResDone,
                                            {'LDAPResult',success,[],[],
                                             asn1_NOVALUE}},
                                           asn1_NOVALUE}}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search reply = searchResDone

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP CHECK: does user have tag administrator?

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP evaluating query: {in_group,"CN=Tags-Administrators,OU=Users & Groups,OU=Company,DC=company,DC=com"}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP evaluating query: {in_group,"CN=Tags-Administrators,OU=Users & Groups,OU=Company,DC=company,DC=com",
                                     "member"}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
        LDAP filling template "CN=Tags-Administrators,OU=Users & Groups,OU=Company,DC=company,DC=com" with
            [{username,<<"user">>},
             {user_dn,"CN=User,OU=Users & Groups,OU=Company,DC=domain,DC=com"}]

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
        LDAP template result: "CN=Tags-Administrators,OU=Users & Groups,OU=Company,DC=company,DC=com"

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search request = {'SearchRequest',
                                            "CN=Tags-Administrators,OU=Users & Groups,OU=Company,DC=company,DC=com",
                                            baseObject,neverDerefAliases,0,0,
                                            false,
                                            {equalityMatch,
                                             {'AttributeValueAssertion',
                                              "member",
                                              "CN=User,OU=Users & Groups,OU=Company,DC=domain,DC=com"}},
                                            ["objectClass"]}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search reply = {ok,
                                          {'LDAPMessage',3,
                                           {searchResDone,
                                            {'LDAPResult',success,[],[],
                                             asn1_NOVALUE}},
                                           asn1_NOVALUE}}

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP network traffic: search reply = searchResDone

=INFO REPORT==== 11-Dec-2014::17:41:19 ===
    LDAP evaluated in_group for "CN=Tags-Administrators,OU=Users & Groups,OU=Company,DC=company,DC=com": false

**Comment by dkiser** [comment]
In the following code we could make the 'scope' a configurable parameter in order to expose baseObject(), singleLevel(), and wholeSubtree() scope options in eldap?

https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L214

**Comment by jakauppila** [comment]
+1

It would be nice to be able to use nested groups.

**Comment by michaelklishin** [comment]
I believe this is a duplicate of https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/16. Please let me know if I'm wrong.

**Comment by Dzol** [comment]
@michaelklishin: If I understand correctly the tickets aren't quite the same.

In [#3](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/3) they're trying to ask if an entry `E` is a member of some `X`, any `X`, as long as that `X` is a member of `Y`. I haven't found a way to do this without knowing `X`. Currently there's no way to iteratively query an entry's attributes.

In [#16](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/16) an entry `E` is a member of `X`, `Y`, and `Z` because it has an attribute with those values.

But: the reason the query above fails is because it's broken not because the query isn't expressing their logic. The ampersand in the string isn't the way to express that logic.

**Comment by hairyhum** [comment]
@dkiser, @Jakauppila can you look at https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/pull/43 and tell what you think about this implementation?

**Comment by dkiser** [comment]
@hairyhum thanks!!!  Will have to try this soon

**Comment by michaelklishin** [comment]
@dkiser it will be in `3.6.3`. We can provide a preview build for you, let me know what package type you need (or if a plugin `.ez` would be sufficient): michael <> RabbitMQ domain.
