### ISSUE TITLE
Undefined config settings cause destructive failures.

### ISSUE THREAD

**Issue by Ayanda-D** [rabbitmq/rabbitmq-auth-backend-ldap#38]
A bit rare for LDAP config settings to be found `undefined`, but seemed to be the case here rabbitmq/rabbitmq-server#781, and we can improve handling as this is currently strict matched. 

One can also argue that defaults should be defined in [rabbitmq_auth_backend_ldap.app.src](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbitmq_auth_backend_ldap.app.src), making this unnecessary.

**Comment by hairyhum** [comment]
I setting is defined in `.app.src` it shouldn't be `undefined`, so as long as we supply default it's safe.
It looks like application has not been properly loaded in rabbitmq/rabbitmq-server#781 which caused multiple issues.

**Comment by Ayanda-D** [comment]
@hairyhum Okay cool. I agree. We'll rely on `.app.src` defaults. & I suppose this makes such failures a good indicator that the application wasn't properly loaded. Thanks for clarifying :)
