### ISSUE TITLE
Make it possible to disable connection pools

### ISSUE THREAD

**Issue by johnfoldager** [rabbitmq/rabbitmq-auth-backend-ldap#40]
We would like to have a configuration option in order to disable the connection pool support because we have an issue which might be because LDAP plugin connects through a Microsoft Azure Load Balancer to a backend LDAP server.

**Comment by hairyhum** [comment]
It's unlikely that connection pools has something to do with load balancers and your issue in general. In your case plugin hasn't started properly and we should not speculate about reasons until we have enough info.

**Comment by hairyhum** [comment]
Connection pool is essential mechanism of LDAP connection and disabling them will not help anyway.

**Comment by johnfoldager** [comment]
I don't agree. LDAP connections works in pre 3.6.0 releases where connection pools are not being used. This request is not related to the other issues I've posted today, so please don't mix them up.

**Comment by hairyhum** [comment]
Sorry if I mix it up. What is the issue with connection pools?

**Comment by hairyhum** [comment]
Looks like we can make connection pools more reliable instead of disabling them.

**Comment by hairyhum** [comment]
@johnfoldager can you please describe issues you have with connection pools that is still persist?

**Comment by johnfoldager** [comment]
I'm really happy to see the support for connection pools for LDAP and we are for sure going to use it when we are confident that it works, however we have so many issues with STOMP, LDAP and clustering and the different pre 3.6 versions of RabbitMQ that we will make a new approach now and be on the latest 3.6.x release/RC/milestone in order to:
1. Test functionality of RabbitMQ + clustering + STOMP + LDAP.
2. Report all the errors and other findings we see to you.
3. Take one issue at a time and concentrate on testing and reporting bugs. However by upgrading we get connection pools etc. and we want to be able to have a newer version with the same functionality but fewer errors, so if we can disable new features like connection pools then it will be easier for us to for example eliminate the load balancer / timeout issue there might or might not be.

An example from this past week:
One of my colleagues have made a load test on the STOMP plugin and it seems to be not as scalable as what we've see previously with AMQP, so work has now begun to make a similar load test on AMQP in order to see the difference when messages comes into queues, because right now it looks like STOMP messages are hold back somewhere before they will arive to a queue when doing load test. I know this has nothing to do with LDAP directly but we want to minimize/remove all the factors that might act differently.

**Comment by michaelklishin** [comment]
At some point there was no connection pooling. It would result in LDAP servers severely overloaded by LDAP connections from RabbitMQ, often bringing them down to their knees, affecting throughput of every operation (because it has to go through authorization), and so on. Those were the days we will not be coming back to. It is possible to configure `pool_size` to be equal to 1, which effectively means "no pooling."
