### ISSUE TITLE
eldap:close/1 fails if TCP connection is already closed/stale as of OTP 18.3

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-ldap#41]
See https://github.com/rabbitmq/rabbitmq-server/issues/781, for example. This issue is about determining what kind of failures in pool processes are not handled gracefully, leading to pool unavailability for one reason or another.

UPD: we've identified an issue with `eldap` in OTP 18.3.

**Comment by hairyhum** [comment]
Initial investigation showed that `eldap` is trying to call `unbind` when being closed by `eldap:close` and if there is no connection during this step it throws exception. This was introduced in `OTP-13327` in `OTP-18.3`
In the LDAP backend code `eldap:close` is called after we receive `{gen_tcp_error, closed}` which means that connection is already closed.
