### ISSUE TITLE
LDAP queries are not cached

### ISSUE THREAD

**Issue by ALTaylor** [rabbitmq/rabbitmq-auth-backend-ldap#47]
Caching ldap queries based on connections and headers would be much more efficient then having to requery each time an action is performed.

**Comment by michaelklishin** [comment]
And a lot more likely to result in unexpected issues.

Duplicate of https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/22, which mentions that we ended up developing https://github.com/rabbitmq/rabbitmq-auth-backend-cache. If you are interested in giving it a try, we can upload a binary release to that repo.
