### ISSUE TITLE
noSuchObject responses are not handled gracefully in OR queries

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-ldap#48]
A user reports getting the following:

```
=ERROR REPORT==== 21-Jun-2016::10:04:21 === 
** Generic server <0.309.0> terminating 
** Last message in was {submit,#Fun<rabbit_auth_backend_ldap.8.133447016>, 
<0.6027.82>,reuse} 
** When Server state == {from,<0.6027.82>,#Ref<0.0.2621442.227430>} 
** Reason for termination == 
** {function_clause, 
[{rabbit_auth_backend_ldap,'-evaluate0/4-fun-1-', 
[{in_group, 
"CN=RabbitMQ-<redacted>-${vhost}-RW,OU=Groups - Rights,OU=<redacted>,DC=<redacted>,DC=com"}, 
{error,noSuchObject}], 
[{file,"src/rabbit_auth_backend_ldap.erl"},{line,162}]}, 
{lists,foldl,3,[{file,"lists.erl"},{line,1262}]}, 
{rabbit_auth_backend_ldap,evaluate0,4, 
[{file,"src/rabbit_auth_backend_ldap.erl"},{line,162}]}, 
{rabbit_auth_backend_ldap,'-with_ldap/3-fun-2-',4, 
[{file,"src/rabbit_auth_backend_ldap.erl"},{line,306}]}, 
{worker_pool_worker,handle_call,3, 
[{file,"src/worker_pool_worker.erl"},{line,108}]}, 
{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1028}]}, 
{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,250}]}]} 
```

We are waiting for more detailed LDAP query logs but looks like query result of `{error, noSuchObject}` isn't handled gracefully by the [OR clause evaluator](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/rabbitmq_v3_6_2/src/rabbit_auth_backend_ldap.erl#L162).

**Comment by michaelklishin** [comment]
Note: this is a follow-up issue to #15. We really should address #45/#46 first => for `3.6.4`.

**Comment by FlyingJ** [comment]
@michaelklishin, I reported this bug to our normal support provider (rather than continuing with the rabbitmq-users Google group). I have been able to replicate the bug (at will) in our development environment. Have you received the cleansed logs with network_unsafe enabled? I uploaded those to our support provider on Wednesday.

**Comment by michaelklishin** [comment]
@FlyingJ we have, thank you. We've started working on this. The issue is pretty well understood at this point I think but we have to do a lot of massaging to our LDAP integration test suite first.

One thing I'd like to clarify: when a query returns an error, do we treat it as "false" in `OR` and `AND` queries? I cannot think of other strategies that are safe.

**Comment by FlyingJ** [comment]
@michaelklishin, thank you for the update!
It makes sense (to me anyway) to treat errors as false and move on with our lives. I do not see any other way to make something like the 'exist' query work.
To clarify my own understanding, wouldn't the in_group, exist queries be returning the "true" or "false" to the OR and AND queries? At that point, those conditionals should function as normally defined.
I need to learn some erlang, so I can read the book...

**Comment by michaelklishin** [comment]
@FlyingJ yes, they should and this is a different manifestation of #15. A lot of things around such queries can be tested better and made more defensive, which is why we are starting with the test suite which hasn't seen much love in years.

**Comment by FlyingJ** [comment]
Understood. Let me know whether I can be any help in the effort.

**Comment by michaelklishin** [comment]
@FlyingJ to set up some expectations, `3.6.3` ships next week so I think this may be for `3.6.4` only. Happy to be wrong but would like to set some expectations.

**Comment by FlyingJ** [comment]
Milestone noted. The bug manifests most readily when using the management UI, or using the more general API requests. We have been working around the problem through user education, versus shutting down the management plugin. That may need to change, if a fix takes longer to come.
I certainly appreciate your efforts!

**Comment by michaelklishin** [comment]
We have some notes on how the issue can be reproduced in the private escalations tracker. I've asked a question there to clarify. Let's continue there :)

**Comment by michaelklishin** [comment]
@FlyingJ thanks to @kjnilsson this will be in `3.6.3 RC2` that ships later today.

**Comment by FlyingJ** [comment]
@michaelklishin thank you for the update!
@kjnilsson thank you for integrating the fix!
