### ISSUE TITLE
Make configuration keys prefix shorter.

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-auth-backend-ldap#59]
Currently we use `rabbitmq_auth_backend_ldap` prefixes to specify `.conf` settings for the plugin.
Other plugins use shorter prefixes like `management`, which may be confusing for some users.

We should consider using `ldap` prefix instead.

Related rabbitmq-users thread https://groups.google.com/forum/#!topic/rabbitmq-users/4ryMHQ_63ek

**Comment by hairyhum** [comment]
Apparently this [example](https://github.com/rabbitmq/rabbitmq-server/blob/master/docs/rabbitmq.conf.example) suggests using `ldap` as a prefix.

**Comment by michaelklishin** [comment]
Good idea, even more convincing that it was user feedback.

**Comment by michaelklishin** [comment]
Note that we can do this for this plugin but not most, for example the HTTP auth one, as it would be too generic.
But thumbs up to this specific idea.

**Comment by hairyhum** [comment]
Maybe `auth_ldap`/`auth_http` will do as a prefix?
And we need to make sure to have all the examples to be correct.
Also we probably want to have startup logs more discoverable to detect such errors.

**Comment by michaelklishin** [comment]
auth_ldap and auth_http sounds like a good middle ground to me.
