### ISSUE TITLE
Ldap connection fails after v3.6.2

### ISSUE THREAD

**Issue by timoch** [rabbitmq/rabbitmq-auth-backend-ldap#63]
Hi,

I am upgrading my rabbitmq setup from a pre-3.6 version. My intention was to upgrade to the latest 3.6.6. However, after the upgrade I kept on getting ldap connection errors like the following :

	=INFO REPORT==== 7-Mar-2017::10:39:51 ===
		LDAP connect error: {error,"connect failed"}

	=INFO REPORT==== 7-Mar-2017::10:39:51 ===
	LDAP DECISION: login for itguard: {error,"connect failed"}

	=INFO REPORT==== 7-Mar-2017::10:39:51 ===
		LDAP network traffic: Connect: "central.fluxys.int" failed {error, econnrefused}

The previous setup worked just fine. I double checked firewalls, I used a different Erlang runtime. In the end I could pinpoint that the ldap connections work up until v3.6.2 but starting with v3.6.3 it doesn't (using the exact same configuration)

Network flow analysis shows no connection is initiated at all to the ldap server. 

Do you have an idea what could cause the issue ?

Thanks,
Julien

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by michaelklishin** [comment]
`econnrefused` is fairly unambiguous: TCP connection to your LDAP server failed. I only remember seeing this once on the mailing list with LDAP TLS connections.

**Comment by timoch** [comment]
Thanks for the quick reply. 
I'll post over to the mailing list. 

`econnrefused` is quite obvious, yes. Since only the rabbitmq versions has changed, my guess is that some default configuration has changed between 3.6.2 and 3.6.3. you mention TLS, that may be it, I don't use TLS so if default changed to using TLS that would explain.

**Comment by timoch** [comment]
Specifying `{ port, 389 }` in the config makes it work. I don't know why I didn't think of it earlier. 
The [rabbitmq documentation](https://www.rabbitmq.com/ldap.html) explicitly mentions that this is the default value (along with ssl and starttls disabled). 

I don't know where that default value is defined though ...

**Comment by michaelklishin** [comment]
@timoch the default as defined in this plugin is [3890](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/Makefile#L21). The LDAP app in Erlang/OTP has its own default but I would be very surprised if the two weren't the same.

Anyhow, our site is [open source](https://github.com/rabbitmq/rabbitmq-website) and we are definitely open to small documentation updates that potentially can save the user a lot of head banging.

**Comment by michaelklishin** [comment]
OK, so the LDAP port indeed is supposed to be [389](https://wiki.wireshark.org/LDAP). Let me do some Git history digging to see when we last changed that default and why.

**Comment by michaelklishin** [comment]
Right, so it was a change in https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/commit/eedce2f1cf8aa8055e6551d01e0b33e7a557cbd9 and the goal is to use a Vagrant VM-provided LDAP server for local integration tests.

So we obviously shouldn't override the default for that but we also can add an explicit port mention to LDAP configuration examples.

**Comment by michaelklishin** [comment]
@timoch OK, apparently the "production" default was changed without any real reason. Will be back to `389` in 3.6.7. Thank you for uncovering it!
