### ISSUE TITLE
Connection purging can fail with a badmatch

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-ldap#66]
See #65.

https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/stable/src/rabbit_auth_backend_ldap.erl#L521 assumes that the connection pool dictionary value is a pair but it isn't, it's a pid instead: see https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/stable/src/rabbit_auth_backend_ldap.erl#L471 and https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/stable/src/rabbit_auth_backend_ldap.erl#L458.

**Comment by hairyhum** [comment]
Fixed in #67
