### ISSUE TITLE
LDAP auto logout

### ISSUE THREAD

**Issue by wbutkow** [rabbitmq/rabbitmq-auth-backend-ldap#7]
To meet PCI regulations and increase general security there should be an auto log out feature which logs out the users after predefined time of inactivity.

**Comment by michaelklishin** [comment]
This can be done by implementing a watchdog process (or process group) and tracking most recent activity for each LDAP server connection.

@wbutkow what kind of timeout would you recommend by default? 1 minute? 10? 30?

**Comment by michaelklishin** [comment]
@hairyhum what if instead of having this an LDAP feature we simply introduced an efficient way of tracking last connection activity (with a precision of maybe 10-30 seconds) and introduced a new plugin that forcefully closes those that have been inactive for too long?

**Comment by hairyhum** [comment]
@michaelklishin RabbitMQ connection closing won't make sense here, because LDAP connections will be still open in the `ldap_pool` worker pool.
The plugin that closes idle connections still can be useful for other purposes.

**Comment by michaelklishin** [comment]
Fair enough.

**Comment by kjnilsson** [comment]
Just to clarify that the PR #53 implements a timeouts for connections between the rabbit server and the LDAP server only. This won't close the idle AMQP connection to the client. The connection to the LDAP server will be re-stablished next time it is required by the AMQP connection. 

It isn't clear to me what expectation the original request was but I have tested this feature as implemented and it works well and is useful for ensuring only active connections also maintain a connection to the LDAP server. Thoughts? /cc @michaelklishin @hairyhum

**Comment by michaelklishin** [comment]
@kjnilsson that's the idea: don't keep LDAP server connections around forever when they are no longer needed.

**Comment by kjnilsson** [comment]
Ok thanks, just wanted to clarify the expectations. Merged.
