### ISSUE TITLE
Is there some LDAP server configure information here?

### ISSUE THREAD

**Issue by eastpav** [rabbitmq/rabbitmq-auth-backend-ldap#77]
Hi:
    I read this plugin document in http://www.rabbitmq.com/ldap.html, but I found no information about LDAP server. Is there some LDAP schema and ldif example files about rabbitmq?
Thx.

**Comment by hairyhum** [comment]
Hi,
Please use [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list for questions. We try to keep github issues for bug reports and feature requests only.
Thank you.

As of your question, there is the `example` directory in this very repository, with `ldif` files used in tests. I believe you can find more examples from people actually using LDAP by asking the mailing list.
