### ISSUE TITLE
in_group does not support "posixGroup"

### ISSUE THREAD

**Issue by phaith** [rabbitmq/rabbitmq-auth-backend-ldap#8]
I would like to use "in_group" like this.

``` erlang
{administrator, {in_group, "cn=administrator,ou=group,dc=test,dc=com", "memberUid"}}
```

This setting doesn't not work correctly.

My company uses posixGroup objectClass as a group for all users. It references to the users in group by memberUid. I saw that "in_group query" support member attribute (which is user_dn). Can this "in_group query" check against specific attribute like memberUid? I've already tried "{in_group, Pattern, AttributeName}" but it compares memberUid with user_dn.

**Comment by michaelklishin** [comment]
I believe your understanding is correct: this is a limitation.

**Comment by Moqume** [comment]
Ah, came across the same issue.  I think the easiest way to resolve this is to allow the end-user to supply a custom filter for the "exists".  Currently it seems to force this to "objectClass".  If one could change this to allow for custom filters that are parsed, say for example "(memberUid=${username})", that would solve it quickly.

**Comment by michaelklishin** [comment]
@Myatu good suggestion, thank you.

**Comment by Dzol** [comment]
The existence of an attribute called _MemberUID_ could be written like so:

``` Erlang
  {match,
    {attribute, DNPattern, "MemberUID"},
    {string, ".*"}
  }
```

Testing the value for equality can be written like this:

``` Erlang
  {equals,
    {attribute, DNPattern, "MemberUID"},
    {string, "foo"}
  }
```

@Myatu : Can that particular query can be written as follows (or a variant of it)?

``` Erlang
  {equals,
    {attribute, DNPattern, "MemberUID"},
    {string, "${username}"}
  }
```

@michaelklishin : Some of the above may be helpful documentation. There's a similar pattern [here](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/etc/rabbit-test.config#L25-L27).

**Comment by michaelklishin** [comment]
@Dzol if this is a new feature, I'd rename `string` to `value`. Or are you saying we only need to update the docs?

**Comment by Dzol** [comment]
@michaelklishin: It's not a new feature but I thought some pointers along these lines may help for the future.

The tests run against the same [configuration](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/etc/rabbit-test.config#L25-L27) that @phaith & @Myatu want (if I understand correctly).

I.e.:

``` Erlang
{match,
  {attribute, "${user_dn}", "description"},
  {string, "can-declare-queues"}}
}
```

It's documented on the plugin's [homepage](http://www.rabbitmq.com/ldap.html) too:

`{attribute, DNPattern, AttributeName}`

> Returns the value of an attribute of an object retrieved from LDAP. As this returns a string rather than a boolean it should be used within a match or equals query. See above for example.

But some additional pointers could help draw attention to those.

**Comment by Dzol** [comment]
There are some small changes on branch [#8](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/tree/rabbitmq-auth-backend-ldap-8), though they're hardly related to the above, which I think are useful.

**Comment by Dzol** [comment]
@michaelklishin: I reviewed the comments (suggestions) above and the documentation at http://www.rabbitmq.com/ldap.html which I think suffices to describe how the queries in question can be formulated. Since the changes on the corresponding branch have been merged: can we close this ticket?
