### ISSUE TITLE
Consider using a finite idle_timeout by default

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-ldap#81]
See [this excellent investigation](https://groups.google.com/forum/#!topic/rabbitmq-users/4Gva3h-yJzM) by Adam Gardner.

Active Directory has connection inactivity timeout of 15 minutes. For reasons that belong to [a separate issue](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/issues/82) (#82), when AD closes a connection from its end, the plugin currently does not recover. Even if that's
addressed, it's worth revisiting the default value. Infinite timeouts have bitten us many times in the past in many different areas.

As with most timeout defaults, it's hard to suggest a good value but here anything in the `300..900` second range sounds reasonable to me.

**Comment by philomory** [comment]
I think 300 seconds is a pretty good target. Besides just being a nice, round number that gives some breathing room below the default timeout on the server side, apparently there are regulated fields in which any value higher than 300 (on the server side) is deemed a violation? https://www.stigviewer.com/stig/windows_server_2012_domain_controller/2014-01-07/finding/V-14831

Frankly, I'm not sure how much we need to care about those sorts of documents (presumably people who are regulated in that sort of manner will not be using default values for this sort of thing), but 5 minutes seems like a good target regardless.

**Comment by michaelklishin** [comment]
Thanks, that's a useful data point. I was going to go with 600 but 300 sounds good.

**Comment by michaelklishin** [comment]
This has been backported to `3.6.16`.
