### ISSUE TITLE
LDAP server-initiated connection closure is not handled gracefully by connection pool

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-ldap#82]
See [this excellent investigation](https://groups.google.com/forum/#!topic/rabbitmq-users/4Gva3h-yJzM) by Adam Gardner.

Active Directory has connection inactivity timeout of 15 minutes. When AD closes a connection from its end, the plugin currently does not recover. The plugin currently uses an infinite `idle_timeout` by default (see #81).

More `gen_tcp` errors should be [handled](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L467-L475) and retried. See [inet POSIX error codes](http://erlang.org/doc/man/inet.html#error_codes) for a extensive list.

Steps to reproduce can be [found on the mailing list](https://groups.google.com/d/msg/rabbitmq-users/4Gva3h-yJzM/ro6PfpAXBgAJ).

**Comment by michaelklishin** [comment]
Some initial findings: the function/scope in question was last modified in #62, https://github.com/rabbitmq/rabbitmq-server/pull/1102. The error handling logic therefore includes `authZ` backend error handling and is not entirely local to the function.

**Comment by michaelklishin** [comment]
Our findings so far:

 * Each connection in the pool maintained by this client has an `idle_timeout` TTL (unless it's set to `infinity`)
 * [This piece of code](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L467-L475) retries on only one `gen_tcp` operation error, `closed`
 * [This piece of code](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/master/src/rabbit_auth_backend_ldap.erl#L504) only propagates a single type of `gen_tcp` error, therefore the code piece above cannot possibly retry on any other error
 * When a connection is closed by the LDAP server, it can enter a bunch of states including `enotconn`, which are returned to the authZ caller in the core. The connection is not purged.
 * When a connection is closed due to a local `idle_timeout`, it is purged and therefore can no longer be used

Handling more `gen_tcp` error types — in fact, all of them — the same way we handle `closed` at the moment makes sense.

Per discussion with @hairyhum @lukebakken @kjnilsson.

**Comment by michaelklishin** [comment]
Unfortunately I cannot reproduce the exact reported issue where connection operations return `enotconn` using OpenLDAP's `idletimeout` setting.

**Comment by philomory** [comment]
@michaelklishin I wasn't able to reproduce it on OpenLDAP either, but put it down to my unfamiliarity with configuring that software. From a packet capture, it looks like Active Directory and OpenLDAP have different behavior when timing out the connection: Active Directory sends a TCP RST packet, whereas OpenLDAP sends a TCP FIN packet.

**Comment by hairyhum** [comment]
@philomory can you please check this alpha build, which should contain a fix from #84  https://bintray.com/rabbitmq/all-dev/rabbitmq-server/3.7.5-alpha.6

**Comment by michaelklishin** [comment]
There is already some feedback from @philomory on the mailing list. #84 alone wasn't sufficient (we didn't expect it to), #84 and #83 together might be but we will be looking into error handling some more before 3.7.5.

**Comment by philomory** [comment]
For reference, I'm off this week and won't be able to perform further testing until I get back.

**Comment by michaelklishin** [comment]
@philomory  would it be possible for you to give [1] a shot in your environment?

Thank you!

1. https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.5-beta.2
