### ISSUE TITLE
Allow anonymous lookup bind in standard config

### ISSUE THREAD

**Issue by dacto** [rabbitmq/rabbitmq-auth-backend-ldap#94]
#### Problem
Specifying `auth_ldap.dn_lookup_bind = anon` is rejected in the standard config, `rabbitmq.conf`.
Only the `as_user` atom is included in the [enum](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/1ae3acb26bd5277ad55630b7d7555eda3b99efc3/priv/schema/rabbitmq_auth_backend_ldap.schema#L109).

Additionally, the [documentation](https://www.rabbitmq.com/ldap.html) mentions anonymous binds but does not specify how to configure the plugin to perform an anonymous lookup bind.
#### Workaround
A functional workaround is specifying this in `advanced.config`:
```
[
  { rabbitmq_auth_backend_ldap, [
    { dn_lookup_bind, anon }
  ]
}
```
#### Summary
Can the...
1. enum be expanded to allow the `anon` in addition to the `as_user` atom?
2. documentation be improved detailing how to configure an anonymous lookup bind?
    (ie: using `auth_ldap.dn_lookup_bind = anon`)

#### Other Info
Versions:
- RabbitMQ: 3.7.5
- rabbitmq_auth_backend_ldap: 3.7.5

Failure:
```
Jun 19 11:14:34 <hostname> rabbitmq-server[10566]: BOOT FAILED
Jun 19 11:14:34 <hostname> rabbitmq-server[10566]: ===========
Jun 19 11:14:34 <hostname> rabbitmq-server[10566]: Config file generation failed 11:14:33.674 [error] Error generating configuration in phase transform_datatypes
Jun 19 11:14:34 <hostname> rabbitmq-server[10566]: 11:14:33.674 [error] Error transforming datatype for: auth_ldap.dn_lookup_bind
Jun 19 11:14:34 <hostname> rabbitmq-server[10566]: 11:14:33.674 [error] "anon" is not a valid enum value, acceptable values are: as_user
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]: BOOT FAILED
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]: ===========
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]: Error description:
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     rabbit:start_it/1 line 450
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     rabbit:boot_error/2 line 857
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     rabbit_lager:log_locations/0 line 59
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     rabbit_lager:ensure_lager_configured/0 line 160
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     rabbit_lager:lager_configured/0 line 167
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     lager:list_all_sinks/0 line 317
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     lager_config:get/2 line 71
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]:     ets:lookup(lager_config, {'_global',handlers})
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]: exit:generate_config_file
Jun 19 11:14:35 <hostname> rabbitmq-server[10566]: Log file(s) (may contain more information):
Jun 19 11:14:37 <hostname> rabbitmq-server[10566]: {"init terminating in do_boot",generate_config_file}
Jun 19 11:14:37 <hostname> rabbitmq-server[10566]: init terminating in do_boot (generate_config_file)
```

**Comment by michaelklishin** [comment]
It can be [any other value](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/d05c008c14089c3b579c9dbc8c983c5426fa0331/src/rabbit_auth_backend_ldap.erl#L720) as well as `anon`.

**Comment by dacto** [comment]
Yes, but the standard config doesn't allow `anon`.
And `anon` is [special](https://github.com/rabbitmq/rabbitmq-auth-backend-ldap/blob/d05c008c14089c3b579c9dbc8c983c5426fa0331/src/rabbit_auth_backend_ldap.erl#L483).

**Comment by michaelklishin** [comment]
`auth_ldap.other_bind` supports `anon` in the config schema as well, so this must be an oversight because finding the line above is not an obvious place to look for the invariants. I'll look into a PR, it should be trivial.
